SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE BANK_ACCOUNT;
DROP TABLE BONUS_RECORD;
DROP TABLE GOLD_TRANS_DETAIL;
DROP TABLE MESSAGE_BOX;
DROP TABLE NOTICE;
DROP TABLE TRANS;
DROP TABLE USERS;




/* Create Tables */

CREATE TABLE BANK_ACCOUNT
(
	ID VARCHAR(30) NOT NULL COMMENT 'id',
	ACCOUNT VARCHAR(50) NOT NULL COMMENT '账号',
	-- 0:否
	-- 1:是默认
	IS_DEF SMALLINT DEFAULT 0 NOT NULL COMMENT '是否默认',
	BANK_NAME VARCHAR(50) NOT NULL COMMENT '开户银行',
	USER_ID VARCHAR(30) NOT NULL COMMENT 'user_id',
	PRIMARY KEY (ID)
) COMMENT = '收款银行账号';


CREATE TABLE BONUS_RECORD
(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id',
	USER_ID VARCHAR(30) NOT NULL COMMENT '玩家id',
	-- 0:市场分红
	-- 1:领导奖
	-- 2:报单奖
	-- 3:推荐奖金
	-- 4:报单奖
	BONUS_TYPE SMALLINT DEFAULT 0 NOT NULL COMMENT '奖金类型',
	GOLD_COINS DECIMAL(10,4) NOT NULL COMMENT '增加金币数',
	GOLD_SEEDS DECIMAL(10,4) DEFAULT 0 NOT NULL COMMENT '金种子增加数',
	LJ DECIMAL(10,4) DEFAULT 0 NOT NULL COMMENT '累计增加',
	CREATE_DATETIME DATETIME NOT NULL COMMENT '创建时间',
	SN VARCHAR(50) NOT NULL COMMENT 'sn玩家编号',
	PRIMARY KEY (ID)
) COMMENT = '奖金记录';


CREATE TABLE GOLD_TRANS_DETAIL
(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id',
	CREATE_DATETIME DATETIME NOT NULL COMMENT '创建时间',
	AUGMENT  DECIMAL(10,4) COMMENT '增加',
	LESSEN DECIMAL(10,4) COMMENT '减少',
	REMARK VARCHAR(50) COMMENT '备注',
	USER_ID VARCHAR(30) NOT NULL COMMENT 'user_id',
	SN VARCHAR(50) NOT NULL COMMENT 'sn玩家编号',
	PRIMARY KEY (ID)
) COMMENT = '金币交易明细';


CREATE TABLE MESSAGE_BOX
(
	ID VARCHAR(30) NOT NULL COMMENT 'id',
	USER_ID VARCHAR(30) NOT NULL COMMENT '玩家id',
	TITLE VARCHAR(50) NOT NULL COMMENT '标题',
	CONTENT TEXT NOT NULL COMMENT '内容',
	CREATE_TIME DATETIME NOT NULL COMMENT '创建时间',
	REPLY TEXT COMMENT '回复',
	REPLY_TIME DATETIME COMMENT '回复时间',
	-- 0:未关闭
	-- 1:已关闭
	STATUS SMALLINT COMMENT '状态',
	PRIMARY KEY (ID)
) COMMENT = '留言，私人邮箱';


CREATE TABLE NOTICE
(
	ID VARCHAR(30) NOT NULL COMMENT 'id',
	-- 0:公告
	-- 1:常见问题
	TYPE SMALLINT DEFAULT 0 NOT NULL COMMENT '类别',
	TITLE VARCHAR(50) NOT NULL COMMENT '标题',
	CONTENT TEXT NOT NULL COMMENT '内容',
	CREATER_ID VARCHAR(30) NOT NULL COMMENT '创建人',
	CREATE_TIME DATETIME NOT NULL COMMENT '创建时间',
	PRIMARY KEY (ID)
) COMMENT = '公告通知';


CREATE TABLE TRANS
(
	ID VARCHAR(30) NOT NULL COMMENT 'id',
	AMT DECIMAL(10,4) DEFAULT 0 NOT NULL COMMENT '金币金额',
	REMARK VARCHAR(50) COMMENT '备注',
	BUY_USER_ID VARCHAR(30) COMMENT '买家玩家',
	BUY_USER_SN VARCHAR(50) COMMENT '买家编号',
	SALE_USER_ID VARCHAR(30) NOT NULL COMMENT '卖出玩家',
	SALE_USER_SN VARCHAR(50) NOT NULL COMMENT '卖家编号',
	CREATE_DATETIME DATETIME NOT NULL COMMENT '创建时间',
	-- 0:未接收
	-- 1:已接收
	IS_RECV SMALLINT DEFAULT 0 NOT NULL COMMENT '买家是否接收',
	IS_CHECK SMALLINT DEFAULT 0 NOT NULL COMMENT '卖家确认',
	-- 0：担保
	-- 1：抢购
	-- 2：转账
	-- 3：系统费用 转账等交易时需要缴纳的手续费给系统账号
	-- 
	-- 转账时，is_recv和is_check都置为1
	TRANS_TYPE SMALLINT DEFAULT 0 NOT NULL COMMENT '交易类型',
	PRIMARY KEY (ID)
) COMMENT = '交易';


CREATE TABLE USERS
(
	ID VARCHAR(30) NOT NULL COMMENT 'id',
	SN VARCHAR(50) NOT NULL UNIQUE COMMENT 'sn玩家编号',
	-- 0:
	-- 1:
	IS_M SMALLINT DEFAULT 0 NOT NULL COMMENT '是否管理用户',
	NICK_NAME VARCHAR(50) NOT NULL COMMENT '玩家昵称',
	REFEREE_SN VARCHAR(50) COMMENT '推荐玩家编号',
	CREATER_ID VARCHAR(30) COMMENT '创建人id',
	-- 0:无级初学咋练
	-- 1:
	-- 2:
	-- 3:
	LEVEL SMALLINT DEFAULT 0 NOT NULL COMMENT '身份等级',
	QQ VARCHAR(0) COMMENT 'qq',
	CREDIT_INDEX SMALLINT DEFAULT 0 NOT NULL COMMENT '信用指数',
	-- 0:未激活
	-- 1:已激活
	STATUS SMALLINT DEFAULT 0 NOT NULL COMMENT '状态',
	-- 0:子帐号
	-- 1:主账号
	ACCOUNT_TYPE SMALLINT DEFAULT 0 NOT NULL COMMENT '帐号类型',
	-- 0:否
	-- 1:是
	REPORT_CENTER SMALLINT DEFAULT 0 NOT NULL COMMENT '是否保单中心',
	PWD1 VARCHAR(50) NOT NULL COMMENT '一级密码',
	PWD2 VARCHAR(50) NOT NULL COMMENT '二级密码',
	LAST_LOGIN_TIME DATETIME COMMENT '上次登录时间',
	LAST_LOGIN_IP VARCHAR(50) COMMENT '上次登录ip',
	LOGIN_TIME DATETIME COMMENT '登录时间',
	LOGIN_IP VARCHAR(50) COMMENT '本次登录ip',
	LOGIN_COUNT INT DEFAULT 0 COMMENT '登录次数',
	IDENTITY_CARD VARCHAR(30) COMMENT '身份证号',
	SAFE_EMAIL VARCHAR(50) COMMENT '安全邮箱',
	GOLD_COIN DECIMAL(10,4) DEFAULT 0 COMMENT '金币',
	GOLD_SEEDS DECIMAL(10,4) DEFAULT 0 COMMENT '金种子',
	-- 0:未出局
	-- 1:已出局
	FHCJ SMALLINT DEFAULT 0 COMMENT '分红出局',
	BONUS_0 DECIMAL(10,4) DEFAULT 0 COMMENT '累计市场分红',
	BONUS_1 DECIMAL(10,4) DEFAULT 0 COMMENT '累计领导奖',
	BONUS_2 DECIMAL(10,4) DEFAULT 0 COMMENT '累计报单奖',
	BONUS_3 DECIMAL(10,4) COMMENT '累计推荐奖',
	REAL_NAME VARCHAR(20) COMMENT '真实姓名',
	MOBILE VARCHAR(20) COMMENT '手机',
	ACCOUNT_COUNT_0 SMALLINT DEFAULT 1 NOT NULL COMMENT '游戏帐号总数',
	ACCOUNT_COUNT_1 SMALLINT DEFAULT 0 NOT NULL COMMENT '直属游戏帐号',
	ACCOUNT_COUNT_2 SMALLINT DEFAULT 1 NOT NULL COMMENT '游戏帐号有效数',
	ACCOUNT_COUNT_3 SMALLINT DEFAULT 0 NOT NULL COMMENT '新增游戏帐号数',
	-- 0
	-- 1 已修改
	MODIFY_PWD SMALLINT DEFAULT 0 COMMENT '是否修改默认密码',
	PRIMARY KEY (ID)
) COMMENT = '用户';



/* Create Foreign Keys */

ALTER TABLE BANK_ACCOUNT
	ADD FOREIGN KEY (USER_ID)
	REFERENCES USERS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE BONUS_RECORD
	ADD FOREIGN KEY (USER_ID)
	REFERENCES USERS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE GOLD_TRANS_DETAIL
	ADD FOREIGN KEY (USER_ID)
	REFERENCES USERS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MESSAGE_BOX
	ADD FOREIGN KEY (USER_ID)
	REFERENCES USERS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE NOTICE
	ADD FOREIGN KEY (CREATER_ID)
	REFERENCES USERS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TRANS
	ADD FOREIGN KEY (SALE_USER_ID)
	REFERENCES USERS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TRANS
	ADD FOREIGN KEY (BUY_USER_ID)
	REFERENCES USERS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



